# Generated by Django 4.2.6 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carisma_app', '0002_alter_empdetails_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetails',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
